# config.yaml
# Configuration AutoCutVideo

# Vidéo
input_video: 'T:\Temp\TeenSexMovs.24.02.07.Lola.Bredly.XXX.1080p.HEVC.x265.PRT[XvX]\TeenSexMovs.24.02.07.Lola.Bredly.XXX.1080p.HEVC.x265.PRT.mkv'
output_dir:  'E:/DocumentsBenoit/Doc DaVinci/timelines/out'

# Matériel & workers
device:                     "cuda:0"
num_workers:                8

# Fréquences & découpe
sample_rate:                0.5     # fps pour échantillonnage rapide
refine_rate:                5.0    # fps pour affinage des bords
min_clip_duration:          5.0    # durée min clip (secondes)
max_gap:                    3.0     # tolérance gap en secondes

# Seuils & filtres
max_face_mask_percentage:   60.0    # % max visage masqué
min_face_confidence:        0.6
min_skin_percentage:        50.0    # % min peau visible sur le corps
gender_filter:              "female" # "homme"/"femme"/"tous"
min_gender_confidence:      0.80
max_head_pitch:             30.0    # deg
max_head_yaw:               80.0    # deg
max_head_roll:              30.0    # deg

# Activation modules
enable_body_detection:      false
enable_skin_detection:      false
enable_face_detection:      true
enable_gender_detection:    true
enable_nsfw:                true
nsfw_mode:                  "high"

# Debug
debug:                      true

# Poids modèles Ultralytics
person_segm_weights:        "E:/DocumentsBenoit/Stable Diffusion/models/ultralytics/segm/person_yolov8n-seg.pt"
face_bbox_weights:          "E:/DocumentsBenoit/Stable Diffusion/models/ultralytics/bbox/face_yolov8n_v2.pt"
skin_segm_weights:          "E:/DocumentsBenoit/Stable Diffusion/models/ultralytics/segm/skin_yolov8n-seg_400.pt"

# ID Hugging Face pour classification de genre
gender_model_id:            "rizvandwiki/gender-classification-2"

# --------------------------------------------------------------------------- #
# Génération automatique des titres (via LMStudio / modèle multimodal)
# --------------------------------------------------------------------------- #
title_generation:
  enabled: true
  model: "mistral-community_pixtral-12b"
  prompt: >-
    describe the picture of a woman giving that criterias only: ethnicity,
    is she nude or wearing lingerie, hair color, age, body shape, breasts size,
    breasts shape, sexual activity type, sex pose name. concatenate answers
    without the criteria name using _ as a separator answers to make a video file title
  endpoint: "http://localhost:1234/v1/chat/completions"
