# config.yaml
# Configuration AutoCutVideo

# Vidéo
input_video: 'T:/Temp/Asian_nude_black_hair_mid_30s_slim_medium_round_cowgirl.mp4'
output_dir:  'E:/DocumentsBenoit/Doc DaVinci/timelines/outTest2'

# Matériel
device:                     "cuda:0"
num_workers:                16

# Fréquences
sample_rate:                2.0   # fps pour échantillonnage rapide
refine_rate:                12.0   # fps pour affinage des bords

# Critères de découpe
min_clip_duration:          10.0    # durée min clip (secondes)
max_gap:                    2  # tolérance gap en secondes

# Seuils
max_face_mask_percentage:  20.0   # % max visage masqué
min_face_confidence:        0.6
min_skin_percentage:        50.0   # % min peau visible sur le corps

# Seuils de rotation de la tête
max_head_pitch:  35.0   # haut / bas
max_head_yaw:    90.0   # gauche / droite
max_head_roll:   30.0   # inclinaison latérale


# Filtre de genre
gender_filter:              "female" # "male"/"female"/"all"
min_gender_confidence:      0.80


enable_nsfw: true
nsfw_mode: "high"

# Activation modules
enable_body_detection:      false
enable_skin_detection:      false
enable_face_detection:      true
enable_gender_detection:    true

# Debug
debug:                      true

# Poids modèles Ultralytics
person_segm_weights:        "E:/DocumentsBenoit/Stable Diffusion/models/ultralytics/segm/person_yolov8n-seg.pt"
face_bbox_weights:          "E:/DocumentsBenoit/Stable Diffusion/models/ultralytics/bbox/face_yolov8n_v2.pt"
skin_segm_weights:          "E:/DocumentsBenoit/Stable Diffusion/models/ultralytics/segm/skin_yolov8n-seg_400.pt"

# ID Hugging Face pour classification de genre
gender_model_id: "rizvandwiki/gender-classification-2"

title_generation:
  enabled: true
  prompt: "describe in one line ..."
  model: "mistral-community_pixtral-12b"
  endpoint: "http://localhost:1234/v1/chat/completions"


